// Attribution for destination photos sourced from Wikimedia Commons.
// Required for CC BY / CC BY-SA reuse -- keep this in sync with any keys
// added to DESTINATION_IMAGES in destination-images.ts that came from
// Commons. The original 6 curated city photos (berat, durres, sarande,
// shkoder, tirane, vlore) are not Commons sourcing and are intentionally
// left out of this file.
export interface DestinationImageCredit {
  title: string;
  author: string;
  license: string;
  sourceUrl: string;
}

export const DESTINATION_IMAGE_CREDITS: Record<string, DestinationImageCredit> = {
  "bajram curri": {
    title: "Bajram Curri from south (WPWTR17).jpg",
    author: "Albinfo",
    license: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bajram_Curri_from_south_(WPWTR17).jpg",
  },
  "ballsh": {
    title: "Ballsh, Mallakastër, Albania 2019 04 – Municipality Hall.jpg",
    author: "Pasztilla aka Attila Terbócs",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ballsh,_Mallakast%C3%ABr,_Albania_2019_04_%E2%80%93_Municipality_Hall.jpg",
  },
  "belsh": {
    title: "Main square of Belsh in Albania in summer.jpg",
    author: "Vyolltsa",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Main_square_of_Belsh_in_Albania_in_summer.jpg",
  },
  "bilisht": {
    title: "Bilishti.jpg",
    author: "Albinfo",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bilishti.jpg",
  },
  "bulqize": {
    title: "Bulqize,Albania.jpg",
    author: "Doni2020",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bulqize,Albania.jpg",
  },
  "burrel": {
    title: "Burrel Square.jpg",
    author: "Albinfo",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Burrel_Square.jpg",
  },
  "cerrik": {
    title: "Cërrik, Albania 2018 03.jpg",
    author: "Pasztilla aka Attila Terbócs",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:C%C3%ABrrik,_Albania_2018_03.jpg",
  },
  "corovode": {
    title: "Çorovodë.jpg",
    author: "Irdi-OP",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%C3%87orovod%C3%AB.jpg",
  },
  "delvina": {
    title: "Kalaja e Delvinës.jpg",
    author: "Albinfo",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kalaja_e_Delvin%C3%ABs.jpg",
  },
  "divjake": {
    title: "Divjaka central square (OSCAL19 trip).jpg",
    author: "Albinfo",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Divjaka_central_square_(OSCAL19_trip).jpg",
  },
  "dropull": {
    title: "Ravenia Goranxi Dropull Albania.jpg",
    author: "Manthos 23",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ravenia_Goranxi_Dropull_Albania.jpg",
  },
  "elbasan": {
    title: "Elbasan Castle, Elbasan, Albania October 2022.jpg",
    author: "Sharon Hahn Darlin",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Elbasan_Castle,_Elbasan,_Albania_October_2022.jpg",
  },
  "erseke": {
    title: "Erseka, Kolonja.jpg",
    author: "Albinfo",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Erseka,_Kolonja.jpg",
  },
  "fier": {
    title: "Parku qendror qyteti i Fierit(Central park City of Fier).jpg",
    author: "Bledian2020",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Parku_qendror_qyteti_i_Fierit(Central_park_City_of_Fier).jpg",
  },
  "finiq": {
    title: "Finiq.jpg",
    author: "Albinfo",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Finiq.jpg",
  },
  "fushe arrez": {
    title: "Fushë-Arrëz.jpg",
    author: "Klein Muçi",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fush%C3%AB-Arr%C3%ABz.jpg",
  },
  "fushe kruje": {
    title: "Fushë-Krujë, Krujë, Albania 2019 02 – Main square.jpg",
    author: "Pasztilla aka Attila Terbócs",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fush%C3%AB-Kruj%C3%AB,_Kruj%C3%AB,_Albania_2019_02_%E2%80%93_Main_square.jpg",
  },
  "gjirokaster": {
    title: "Gjirokastёr - roofs.JPG",
    author: "Pudelek",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gjirokast%D1%91r_-_roofs.JPG",
  },
  "golem": {
    title: "Golem, Qarku i Tiranës (Tirana County), Albania - Miami Beach.jpg",
    author: "Sharon Hahn Darlin",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Golem,_Qarku_i_Tiran%C3%ABs_(Tirana_County),_Albania_-_Miami_Beach.jpg",
  },
  "gramsh": {
    title: "Gramsh from the air.jpg",
    author: "Albinfo",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gramsh_from_the_air.jpg",
  },
  "himare": {
    title: "Himara 2021.jpg",
    author: "Albinfo",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Himara_2021.jpg",
  },
  "kamez": {
    title: "Kamëz, Albania 01 - Town Center.jpg",
    author: "Pasztilla aka Attila Terbócs",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kam%C3%ABz,_Albania_01_-_Town_Center.jpg",
  },
  "kavaje": {
    title: "Shkëmbi i Kavajës.jpg",
    author: "Albinfo",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Shk%C3%ABmbi_i_Kavaj%C3%ABs.jpg",
  },
  "kelcyre": {
    title: "Vjosa at Këlcyra- Black Water.jpg",
    author: "Albinfo",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Vjosa_at_K%C3%ABlcyra-_Black_Water.jpg",
  },
  "klos": {
    title: "Klos in Mat.jpg",
    author: "Albinfo",
    license: "CC BY 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Klos_in_Mat.jpg",
  },
  "konispol": {
    title: "Konispol.jpg",
    author: "Albinfo",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Konispol.jpg",
  },
  "koplik": {
    title: "Koplik, Albania.jpg",
    author: "CivArmy",
    license: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Koplik,_Albania.jpg",
  },
  "korce": {
    title: "2014 Korçë , Pazari i Vjetër.JPG",
    author: "Berberi PG",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2014_Kor%C3%A7%C3%AB_,_Pazari_i_Vjet%C3%ABr.JPG",
  },
  "kruje": {
    title: "Muzeum Skanderbega w Kruji 2.jpg",
    author: "Marcin Konsek",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Muzeum_Skanderbega_w_Kruji_2.jpg",
  },
  "krume": {
    title: "Krumë, Has, Albania 2018 04.jpg",
    author: "Pasztilla aka Attila Terbócs",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Krum%C3%AB,_Has,_Albania_2018_04.jpg",
  },
  "kucove": {
    title: "Kuçovë Main street.jpg",
    author: "Albinfo",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ku%C3%A7ov%C3%AB_Main_street.jpg",
  },
  "kukes": {
    title: "Kukës and Gora mountains (WPWTR17).jpg",
    author: "Albinfo",
    license: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kuk%C3%ABs_and_Gora_mountains_(WPWTR17).jpg",
  },
  "lac": {
    title: "Laç monastery (WPWTR16).JPG",
    author: "Albinfo",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:La%C3%A7_monastery_(WPWTR16).JPG",
  },
  "leskovik": {
    title: "Cultural Centre of Leskovik.jpg",
    author: "Leeturtle",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cultural_Centre_of_Leskovik.jpg",
  },
  "lezhe": {
    title: "Lezhë, Albania – Skanderbeg Memorial 2016 03.jpg",
    author: "Pasztilla aka Attila Terbócs",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lezh%C3%AB,_Albania_%E2%80%93_Skanderbeg_Memorial_2016_03.jpg",
  },
  "libohove": {
    title: "Libohova Castle, Albania 2017-08 01.jpg",
    author: "Pasztilla aka Attila Terbócs",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Libohova_Castle,_Albania_2017-08_01.jpg",
  },
  "librazhd": {
    title: "Librazhd Qender.jpg",
    author: "Albinfo",
    license: "CC BY-SA 2.5",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Librazhd_Qender.jpg",
  },
  "lushnje": {
    title: "Lushnjë, Albania 2019 21 – Shqiponja Monument.jpg",
    author: "Pasztilla aka Attila Terbócs",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lushnj%C3%AB,_Albania_2019_21_%E2%80%93_Shqiponja_Monument.jpg",
  },
  "maliq": {
    title: "Maliq Bridge.jpg",
    author: "Albinfo",
    license: "CC BY 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Maliq_Bridge.jpg",
  },
  "mamurrasi": {
    title: "Mamurras, Albania 04.jpg",
    author: "Pasztilla aka Attila Terbócs",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mamurras,_Albania_04.jpg",
  },
  "manez": {
    title: "Flags in Manëz.jpg",
    author: "Albinfo",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Flags_in_Man%C3%ABz.jpg",
  },
  "memaliaj": {
    title: "Memaliaj, Albania 2019 02.jpg",
    author: "Pasztilla aka Attila Terbócs",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Memaliaj,_Albania_2019_02.jpg",
  },
  "milot": {
    title: "Miloti.jpg",
    author: "Albinfo",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Miloti.jpg",
  },
  "mirdite": {
    title: "Mirditë District, Albania - panoramio (1).jpg",
    author: "pmlleshi",
    license: "CC BY 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mirdit%C3%AB_District,_Albania_-_panoramio_(1).jpg",
  },
  "orikum": {
    title: "Orikum (and Dukat i Ri), Vlorë County, Albania.jpg",
    author: "Sharon Hahn Darlin",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Orikum_(and_Dukat_i_Ri),_Vlor%C3%AB_County,_Albania.jpg",
  },
  "patos": {
    title: "Patos, Albania 2016 01.jpg",
    author: "Pasztilla aka Attila Terbócs",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Patos,_Albania_2016_01.jpg",
  },
  "peqin": {
    title: "Peqin, Albania – Castle 1995 01.jpg",
    author: "Pasztilla aka Attila Terbócs",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Peqin,_Albania_%E2%80%93_Castle_1995_01.jpg",
  },
  "permet": {
    title: "Përmet, Albania Panorama.jpg",
    author: "Holger Adams",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:P%C3%ABrmet,_Albania_Panorama.jpg",
  },
  "peshkopi": {
    title: "Peshkopi, Albania 2018-04 01.jpg",
    author: "Pasztilla aka Attila Terbócs",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Peshkopi,_Albania_2018-04_01.jpg",
  },
  "pogradec": {
    title: "Pogradec, Albania 2023.jpg",
    author: "Killographer",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pogradec,_Albania_2023.jpg",
  },
  "polican": {
    title: "Poliçan.jpg",
    author: "Albinfo",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Poli%C3%A7an.jpg",
  },
  "prrenjas": {
    title: "Prrenjas 02.jpg",
    author: "Klein Muçi",
    license: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Prrenjas_02.jpg",
  },
  "puke": {
    title: "Pukë square 12.jpg",
    author: "Arianit",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Puk%C3%AB_square_12.jpg",
  },
  "rinas (aeroport)": {
    title: "Rinas-Airport-New-Terminal.jpg",
    author: "Albinfo",
    license: "CC BY-SA 2.5",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rinas-Airport-New-Terminal.jpg",
  },
  "roskovec": {
    title: "Roskovec 01.jpg",
    author: "Klein Muçi",
    license: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Roskovec_01.jpg",
  },
  "rreshen": {
    title: "Rreshen (WPWTR17).jpg",
    author: "Albinfo",
    license: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rreshen_(WPWTR17).jpg",
  },
  "rrogozhine": {
    title: "Rrogozhina.jpg",
    author: "Albinfo",
    license: "CC BY-SA 2.5",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rrogozhina.jpg",
  },
  "rubik": {
    title: "View of Rubik from Church of Rubik3.jpg",
    author: "Arianit",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:View_of_Rubik_from_Church_of_Rubik3.jpg",
  },
  "selenice": {
    title: "Selenica from the distance 2.jpg",
    author: "Albinfo",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Selenica_from_the_distance_2.jpg",
  },
  "shengjin": {
    title: "Shëngjin 2020 aerial view.jpg",
    author: "Albinfo",
    license: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sh%C3%ABngjin_2020_aerial_view.jpg",
  },
  "shijak": {
    title: "Shijak central square (OSCAL19 trip).jpg",
    author: "Albinfo",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Shijak_central_square_(OSCAL19_trip).jpg",
  },
  "sukth": {
    title: "Sukth i Ri Main Road - Mapillary (3131407893840738) (cropped).jpg",
    author: "atpl_pilot @ Mapillary",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sukth_i_Ri_Main_Road_-_Mapillary_(3131407893840738)_(cropped).jpg",
  },
  "tepelene": {
    title: "Tepelene 017.jpg",
    author: "Arianit",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tepelene_017.jpg",
  },
  "ura vajgurore": {
    title: "Ura Vajgurore Sheshi qendror.jpg",
    author: "Albinfo",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ura_Vajgurore_Sheshi_qendror.jpg",
  },
  "vau i dejes": {
    title: "VauDeja and mountains (WPWTR16).jpg",
    author: "Albinfo",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:VauDeja_and_mountains_(WPWTR16).jpg",
  },
  "velipoje": {
    title: "Velipojë.jpg",
    author: "Albinfo",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Velipoj%C3%AB.jpg",
  },
  "vore": {
    title: "Vorë, Albania 2019 01.jpg",
    author: "Pasztilla aka Attila Terbócs",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Vor%C3%AB,_Albania_2019_01.jpg",
  },
};
